### ISSUE TITLE
Home Assistant MQTT DSMR error.

### ISSUE THREAD

**Issue by mihaiaka** [mhendriks/DSMR-API-V2#4]
Hello Martijn,

My home assistant is complaing about the timetag (probably because of the inclusion of the "S" >> "non-numeric value"), as you can see in this HA log:

Logger: homeassistant.components.mqtt.models
Source: components/sensor/__init__.py:583
Integration: MQTT (documentation, issues)
First occurred: 19:16:06 (46 occurrences)
Last logged: 19:20:18

Exception raised when updating state of sensor.dsmr_last_update, topic: 'DSMR-API/timestamp' with payload: b'{"timestamp":[{"value":"230507191952S"}]}'
Exception raised when updating state of sensor.dsmr_last_update, topic: 'DSMR-API/timestamp' with payload: b'{"timestamp":[{"value":"230507191957S"}]}'
Exception raised when updating state of sensor.dsmr_last_update, topic: 'DSMR-API/timestamp' with payload: b'{"timestamp":[{"value":"230507192003S"}]}'
Exception raised when updating state of sensor.dsmr_last_update, topic: 'DSMR-API/timestamp' with payload: b'{"timestamp":[{"value":"230507192009S"}]}'
Exception raised when updating state of sensor.dsmr_last_update, topic: 'DSMR-API/timestamp' with payload: b'{"timestamp":[{"value":"230507192015S"}]}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: '2023-05-07 19:16:02'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 270, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.dsmr_last_update has device class None, state class measurement unit  and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: 2023-05-07 19:16:02 (<class 'str'>)

The entity in home assistant, being unable to read that, turns to "unknown", but the log is being flooded with the above error.
![image](https://github.com/mhendriks/DSMR-API-V2/assets/50486008/141370da-abb1-47ef-b2cc-397c69a41e90)

TELNET-ing to the P1 module, it also logs something about this:
###going on forever like this every 2 seconds:
[Time----][FreeHeap/mBlck][Function----(line):
[13:56:10][  21152| 19840] processSlimm(  57): telegramCount=[118807] telegramErrors=[6] bufferlength=[905]
[13:56:10][  21152| 19840] processTeleg( 103): Telegram[118807]=>DSMRdata.timestamp[230519135611S]

For now, i've disable the "DSMR Last Update" entity so it will stop flooding the HA logs, but it's still filling up the screen on telnet via P1.

Is there something you can assist with from your end?
I'm already on version 3.5.7. (thank you for that)

Looking forward, thank you very much.
Mihai.

**Comment by mhendriks** [comment]
The telnet output is normal behaviour. This is the logging. Looking okay.

The b before the payload ( `b'{"timestamp":[{"value":"230507191952S"}]}'` ) is strange. Shouldn't be there. 

In the logging it looks like HA parsing the timestamp to an integer value. This will fail. Better is to parse it to a date object like this:

`strptime(value_json.timestamp[0].value[0:12], \'%y%m%d%H%M%S\')`

**Comment by AllardKatan** [comment]
I can confirm this issue. Similar error message on my HomeAssistant instance.

**Comment by mhendriks** [comment]
issue with the Auto Discovery is solved in release 3.5.9.  Issue raised due to changes in HA updates.

**Comment by AllardKatan** [comment]
I was running 3.5.9 for a while and I thought the issue was solved. But after looking into it a bit more, I am still getting a lot of these same error messages. For some reason, some of the messages get through, because I am getting correct values in my energy dashboard, but the update rate seemed slower than what I thought it should be.
I went into the logs and noticed this same error occuring many times. 
Then I made things worse by attempting to upgrade to the latest version. I downloaded the latest binary from https://docs.smart-stuff.nl/v/p1-dongle-api/geavanceerd/software-update and installed it via the web interface. Now the dongle has disappeared from my WLAN....
